"""Initial migration

Revision ID: 948144f2b5be
Revises: 
Create Date: 2025-12-28 19:12:29.013150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948144f2b5be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_created', 'audit_log', ['action', 'created_at'], unique=False)
    op.create_index('idx_user_created', 'audit_log', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('max_channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('channel_username', sa.String(), nullable=True),
    sa.Column('channel_title', sa.String(), nullable=False),
    sa.Column('bot_added_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_max_channels_channel_id'), 'max_channels', ['channel_id'], unique=False)
    op.create_index(op.f('ix_max_channels_id'), 'max_channels', ['id'], unique=False)
    op.create_index(op.f('ix_max_channels_user_id'), 'max_channels', ['user_id'], unique=False)
    op.create_table('telegram_channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_username', sa.String(), nullable=True),
    sa.Column('channel_title', sa.String(), nullable=False),
    sa.Column('bot_added_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_channels_channel_id'), 'telegram_channels', ['channel_id'], unique=True)
    op.create_index(op.f('ix_telegram_channels_id'), 'telegram_channels', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_channels_user_id'), 'telegram_channels', ['user_id'], unique=False)
    op.create_table('crossposting_links',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('max_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['max_channel_id'], ['max_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['telegram_channel_id'], ['telegram_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_channel_id', 'max_channel_id', name='uq_telegram_max_channels')
    )
    op.create_index('idx_is_enabled', 'crossposting_links', ['is_enabled'], unique=False)
    op.create_index('idx_max_channel', 'crossposting_links', ['max_channel_id'], unique=False)
    op.create_index('idx_telegram_channel', 'crossposting_links', ['telegram_channel_id'], unique=False)
    op.create_index(op.f('ix_crossposting_links_id'), 'crossposting_links', ['id'], unique=False)
    op.create_index(op.f('ix_crossposting_links_is_enabled'), 'crossposting_links', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_crossposting_links_max_channel_id'), 'crossposting_links', ['max_channel_id'], unique=False)
    op.create_index(op.f('ix_crossposting_links_telegram_channel_id'), 'crossposting_links', ['telegram_channel_id'], unique=False)
    op.create_index(op.f('ix_crossposting_links_user_id'), 'crossposting_links', ['user_id'], unique=False)
    op.create_table('failed_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('crossposting_link_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crossposting_link_id'], ['crossposting_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retry', 'failed_messages', ['retry_count', 'last_retry_at'], unique=False)
    op.create_index(op.f('ix_failed_messages_crossposting_link_id'), 'failed_messages', ['crossposting_link_id'], unique=False)
    op.create_index(op.f('ix_failed_messages_id'), 'failed_messages', ['id'], unique=False)
    op.create_index(op.f('ix_failed_messages_resolved_at'), 'failed_messages', ['resolved_at'], unique=False)
    op.create_table('messages_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('crossposting_link_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('max_message_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crossposting_link_id'], ['crossposting_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crossposting_link_id', 'telegram_message_id', name='uq_link_message')
    )
    op.create_index('idx_created_at', 'messages_log', ['created_at'], unique=False)
    op.create_index('idx_link_created', 'messages_log', ['crossposting_link_id', 'created_at'], unique=False)
    op.create_index('idx_status', 'messages_log', ['status'], unique=False)
    op.create_index(op.f('ix_messages_log_created_at'), 'messages_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_log_id'), 'messages_log', ['id'], unique=False)
    op.create_index(op.f('ix_messages_log_status'), 'messages_log', ['status'], unique=False)
    op.create_index(op.f('ix_messages_log_telegram_message_id'), 'messages_log', ['telegram_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_log_telegram_message_id'), table_name='messages_log')
    op.drop_index(op.f('ix_messages_log_status'), table_name='messages_log')
    op.drop_index(op.f('ix_messages_log_id'), table_name='messages_log')
    op.drop_index(op.f('ix_messages_log_created_at'), table_name='messages_log')
    op.drop_index('idx_status', table_name='messages_log')
    op.drop_index('idx_link_created', table_name='messages_log')
    op.drop_index('idx_created_at', table_name='messages_log')
    op.drop_table('messages_log')
    op.drop_index(op.f('ix_failed_messages_resolved_at'), table_name='failed_messages')
    op.drop_index(op.f('ix_failed_messages_id'), table_name='failed_messages')
    op.drop_index(op.f('ix_failed_messages_crossposting_link_id'), table_name='failed_messages')
    op.drop_index('idx_retry', table_name='failed_messages')
    op.drop_table('failed_messages')
    op.drop_index(op.f('ix_crossposting_links_user_id'), table_name='crossposting_links')
    op.drop_index(op.f('ix_crossposting_links_telegram_channel_id'), table_name='crossposting_links')
    op.drop_index(op.f('ix_crossposting_links_max_channel_id'), table_name='crossposting_links')
    op.drop_index(op.f('ix_crossposting_links_is_enabled'), table_name='crossposting_links')
    op.drop_index(op.f('ix_crossposting_links_id'), table_name='crossposting_links')
    op.drop_index('idx_telegram_channel', table_name='crossposting_links')
    op.drop_index('idx_max_channel', table_name='crossposting_links')
    op.drop_index('idx_is_enabled', table_name='crossposting_links')
    op.drop_table('crossposting_links')
    op.drop_index(op.f('ix_telegram_channels_user_id'), table_name='telegram_channels')
    op.drop_index(op.f('ix_telegram_channels_id'), table_name='telegram_channels')
    op.drop_index(op.f('ix_telegram_channels_channel_id'), table_name='telegram_channels')
    op.drop_table('telegram_channels')
    op.drop_index(op.f('ix_max_channels_user_id'), table_name='max_channels')
    op.drop_index(op.f('ix_max_channels_id'), table_name='max_channels')
    op.drop_index(op.f('ix_max_channels_channel_id'), table_name='max_channels')
    op.drop_table('max_channels')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index('idx_user_created', table_name='audit_log')
    op.drop_index('idx_action_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

